title: 'Entry '
description: Stage 1HNGi-7
template:
  repo: entry-template
  name: entry
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
